### ISSUE TITLE
docker-compose下如何保存用户信息？

### ISSUE THREAD

**Issue by elmagnificogi** [sapicd/sapic#17]
docker-compose下如何保存用户信息？

我直接docker-compose down 然后重新build了一下,再启动（我改了一下ui的size）

然后我就发现直接用户信息全丢，还要重建用户，但是之前的记录已经没有了。
虽然图片都还在，还能引用外链，但是之前的站点设置、用户设置、token啥的全丢了。

docker-compose中能否保留一下这些数据。

我看了一下备份数据的办法，是再建一个才能平移过去，也就是同时有2个sapic，但是我这个是基于原来那个重新build，怎么办

**Comment by elmagnificogi** [comment]
那能改一下把文件也同时挂载出来吧？这样方便一些

**Comment by staugur** [comment]
考虑增加2个yml，带redis和不带的

**Comment by elmagnificogi** [comment]
我试了一下 加个volume就行了
```
version: '3'
services:
  webapp:
    build: .
    restart: always
    ports:
      - "9514:9514"
    environment:
      - sapic_redis_url=redis://@redis:6379
      # 设置信任代理标头
      #- sapic_proxyfix=true
    volumes:
      - static:/picbed/static/
      - /data/picbed/:/picbed/static/upload/
    depends_on:
      - "redis"
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - /data/picbed/redis/data/:/data/
volumes:
  static:
```

已经有数据的，最好先进到容器里，先把appendonly.aof复制出来
`docker cp '容器的id':/data/appendonly.aof /data/picbed/redis/data/appendonly.aof`

然后修改docker-compose，重启啥的就没关系了。

我就不PR了，有空你也改下吧
